
// Navigation
export const NAV_LINKS = [
  { id: 'home', label: 'Home', path: '/' },
  { id: 'properties', label: 'Properties', path: '/properties' },
  { id: 'about', label: 'About', path: '/about' },
  { id: 'contact', label: 'Contact', path: '/contact' },
];

// Sample Property Data
export const FEATURED_PROPERTIES = [
  {
    id: 1,
    title: 'Modern Minimalist Villa',
    address: '123 Palm Avenue, Miami, FL',
    price: 1250000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    description: 'Contemporary villa with clean lines and open concept living spaces.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: true,
    type: 'residential',
    isNew: false,
  },
  {
    id: 2,
    title: 'Luxury Penthouse',
    address: '456 Skyline Drive, New York, NY',
    price: 3500000,
    bedrooms: 3,
    bathrooms: 3.5,
    area: 3200,
    description: 'Stunning penthouse with panoramic city views and premium finishes.',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: true,
    type: 'residential',
    isNew: false,
  },
  {
    id: 3,
    title: 'Seaside Retreat',
    address: '789 Ocean Boulevard, Malibu, CA',
    price: 4750000,
    bedrooms: 5,
    bathrooms: 4,
    area: 4100,
    description: 'Breathtaking beachfront property with direct access to private beach.',
    image: 'https://images.unsplash.com/photo-1600607687644-4e4512d79987?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: true,
    type: 'residential',
    isNew: false,
  },
  {
    id: 4,
    title: 'Urban Loft Apartment',
    address: '321 Downtown Street, Chicago, IL',
    price: 875000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1800,
    description: 'Stylish loft in the heart of the city with industrial design elements.',
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: true,
    type: 'residential',
    isNew: false,
  },
];

export const ALL_PROPERTIES = [
  ...FEATURED_PROPERTIES,
  {
    id: 5,
    title: 'Mountain Cabin',
    address: '555 Pine Trail, Aspen, CO',
    price: 950000,
    bedrooms: 3,
    bathrooms: 2,
    area: 2100,
    description: 'Cozy mountain retreat with stunning views and rustic charm.',
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: false,
    type: 'residential',
    isNew: false,
  },
  {
    id: 6,
    title: 'Historic Brownstone',
    address: '777 Heritage Lane, Boston, MA',
    price: 1850000,
    bedrooms: 4,
    bathrooms: 3.5,
    area: 3000,
    description: 'Beautifully restored historic home with modern amenities.',
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: false,
    type: 'residential',
    isNew: false,
  },
  {
    id: 7,
    title: 'Waterfront Estate',
    address: '888 Lake View Drive, Seattle, WA',
    price: 5250000,
    bedrooms: 6,
    bathrooms: 5,
    area: 5500,
    description: 'Expansive estate with private dock and incredible water views.',
    image: 'https://images.unsplash.com/photo-1600607687920-4e4a59aaf650?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: false,
    type: 'residential',
    isNew: false,
  },
  {
    id: 8,
    title: 'Desert Oasis',
    address: '999 Saguaro Road, Scottsdale, AZ',
    price: 1650000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3800,
    description: 'Modern desert home with infinity pool and mountain views.',
    image: 'https://images.unsplash.com/photo-1600566753104-685f4b68f975?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: false,
    type: 'residential',
    isNew: false,
  },
  // New Residential Properties
  {
    id: 9,
    title: 'Smart Home Paradise',
    address: '123 Tech Lane, San Jose, CA',
    price: 2100000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2900,
    description: 'Ultra-modern smart home with integrated automation systems throughout.',
    image: 'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: false,
    type: 'residential',
    isNew: true,
  },
  {
    id: 10,
    title: 'Lakeside Cottage',
    address: '456 Shoreline Drive, Lake Tahoe, NV',
    price: 895000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1850,
    description: 'Charming cottage with stunning lake views and private dock access.',
    image: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: false,
    type: 'residential',
    isNew: true,
  },
  {
    id: 11,
    title: 'Urban Micro Apartment',
    address: '789 Compact Street, San Francisco, CA',
    price: 675000,
    bedrooms: 1,
    bathrooms: 1,
    area: 550,
    description: 'Innovative micro apartment with transformable spaces and smart storage solutions.',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: false,
    type: 'residential',
    isNew: true,
  },
  {
    id: 12,
    title: 'Garden Villa',
    address: '321 Botanical Way, Portland, OR',
    price: 1250000,
    bedrooms: 3,
    bathrooms: 2.5,
    area: 2250,
    description: 'Eco-friendly home with extensive gardens and sustainable features.',
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: false,
    type: 'residential',
    isNew: true,
  },
  // Commercial Properties
  {
    id: 13,
    title: 'Downtown Office Tower',
    address: '100 Business Plaza, Chicago, IL',
    price: 12500000,
    bedrooms: 0,
    bathrooms: 8,
    area: 25000,
    description: 'Prime commercial office tower in the heart of the financial district.',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: true,
    type: 'commercial',
    isNew: false,
  },
  {
    id: 14,
    title: 'Retail Shopping Center',
    address: '200 Market Street, Austin, TX',
    price: 8750000,
    bedrooms: 0,
    bathrooms: 12,
    area: 35000,
    description: 'Bustling retail center with high foot traffic and multiple storefronts.',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: false,
    type: 'commercial',
    isNew: false,
  },
  {
    id: 15,
    title: 'Boutique Hotel',
    address: '300 Hospitality Road, Miami, FL',
    price: 15500000,
    bedrooms: 45,
    bathrooms: 48,
    area: 28000,
    description: 'Elegant boutique hotel with restaurant and rooftop pool facilities.',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: false,
    type: 'commercial',
    isNew: false,
  },
  {
    id: 16,
    title: 'Industrial Warehouse',
    address: '400 Logistics Avenue, Dallas, TX',
    price: 4200000,
    bedrooms: 0,
    bathrooms: 4,
    area: 45000,
    description: 'Modern warehouse facility with loading docks and office space.',
    image: 'https://images.unsplash.com/photo-1565626424178-c699f6601afd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: false,
    type: 'commercial',
    isNew: false,
  },
  {
    id: 17,
    title: 'Medical Office Building',
    address: '500 Healthcare Drive, Boston, MA',
    price: 7850000,
    bedrooms: 0,
    bathrooms: 15,
    area: 18000,
    description: 'Purpose-built medical facility with specialized infrastructure and parking.',
    image: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: true,
    type: 'commercial',
    isNew: true,
  },
  {
    id: 18,
    title: 'Co-Working Complex',
    address: '600 Innovation Way, Seattle, WA',
    price: 6500000,
    bedrooms: 0,
    bathrooms: 10,
    area: 15000,
    description: 'Modern co-working space with flexible offices and communal areas.',
    image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: false,
    type: 'commercial',
    isNew: true,
  },
  // New Listings (Mix of residential and commercial)
  {
    id: 19,
    title: 'Sustainable Eco-Office',
    address: '123 Green Street, Portland, OR',
    price: 3850000,
    bedrooms: 0,
    bathrooms: 6,
    area: 8500,
    description: 'LEED-certified office building with solar panels and rainwater harvesting.',
    image: 'https://images.unsplash.com/photo-1545253088-bfcabd8c8862?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: false,
    type: 'commercial',
    isNew: true,
  },
  {
    id: 20,
    title: 'Smart Apartment Building',
    address: '789 Connected Lane, Denver, CO',
    price: 7250000,
    bedrooms: 24,
    bathrooms: 26,
    area: 32000,
    description: 'Multi-unit residential building with integrated smart home technology.',
    image: 'https://images.unsplash.com/photo-1460317442991-0ec209397118?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: false,
    type: 'residential',
    isNew: true,
  },
  {
    id: 21,
    title: 'Mixed-Use Development',
    address: '456 Urban Center, Nashville, TN',
    price: 9500000,
    bedrooms: 12,
    bathrooms: 18,
    area: 28000,
    description: 'Live-work complex with retail on ground floor and residential units above.',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: true,
    type: 'commercial',
    isNew: true,
  },
  {
    id: 22,
    title: 'Tiny Home Community',
    address: '321 Minimal Road, Asheville, NC',
    price: 2100000,
    bedrooms: 25,
    bathrooms: 25,
    area: 12500,
    description: 'Collection of custom-designed tiny homes with shared community spaces.',
    image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    featured: false,
    type: 'residential',
    isNew: true,
  },
];

// Company information
export const COMPANY_INFO = {
  name: 'Estate Flow',
  founded: 2015,
  mission: 'To connect discerning clients with extraordinary properties through a seamless and personalized experience.',
  description: 'Estate Flow is a premium real estate firm specializing in luxury properties across the United States. Our curated approach and attention to detail ensure that each client finds their perfect space.',
  team: [
    {
      name: 'Alex Morgan',
      position: 'Founder & CEO',
      image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
    },
    {
      name: 'Jordan Chen',
      position: 'Principal Broker',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
    },
    {
      name: 'Taylor Williams',
      position: 'Director of Acquisitions',
      image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
    },
    {
      name: 'Jamie Richardson',
      position: 'Head of Marketing',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
    },
  ],
};

// Contact information
export const CONTACT_INFO = {
  email: 'info@estateflow.com',
  phone: '+1 (555) 123-4567',
  address: '1234 Luxury Lane, Suite 500, New York, NY 10001',
  social: {
    instagram: 'https://instagram.com',
    twitter: 'https://twitter.com',
    facebook: 'https://facebook.com',
    linkedin: 'https://linkedin.com',
  },
};
